var AGENTS = 'AGENTS',
    SPYMASTER = 'SPYMASTER',
    // actions
    SEED_CHANGE = 'SEED_CHANGE',
    PLAYER_CHANGE = 'PLAYER_CHANGE',
    SETUP_FORM_SUBMIT = 'SETUP_FORM_SUBMIT',
    START_GAME = 'START_GAME';
